import Header from '@/components/Header';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className="min-h-screen">
                <Header />
                <main className="flex flex-col px-4 lg:px-6 py-3 mx-auto max-w-2xl md:max-w-4xl lg:max-w-7xl">
                    {children}
                </main>
            </body>
        </html>
    );
}
